### ISSUE TITLE
Add function Get-passwordstatePassword

### ISSUE THREAD

**Issue by 2Dman** [dnewsholme/PasswordState-Management#1]
This would get all passwords of a certain list, you would need to add the "?QueryAll"

For example:

$PasswordstateUrl = "https://passwordstateqa/winapi/passwords/" + $_ + "?QueryAll"
$Passwords += Invoke-Restmethod -Method GET -Uri $PasswordstateUrl -UseDefaultCredentials

if you would like, i can make a pull request to look into this ?

**Comment by dnewsholme** [comment]
Sounds a good idea. If you would like to do this feel free.

I've used Get-PasswordStateResource to retrieve from the api for all other functions to keep it easier to maintain.

**Comment by dnewsholme** [comment]
Closed in #3
