### ISSUE TITLE
Get-PasswordStatePassword only returns a single password when multiple are expected

### ISSUE THREAD

**Issue by trir262** [dnewsholme/PasswordState-Management#104]
There a difference in behavior in v4.4.9 and 4.4.11.
Here are the steps I executed:
~~~Powershell
Install-Module Passwordstate-Management -RequiredVersion 4.4.9
Import-module Passwordstate-Management -RequiredVersion 4.4.9
Set-PasswordStateEnvironment -Baseuri 'https://pws.localhost.com' -WindowsAuthOnly -path c:\temp\4_9
$pwlist=Get-PasswordStateList -PasswordList 'pwlistname'
(Get-PasswordStatePassword -PasswordListID $pwlist.PasswordListID).count
~~~

~~~Powershell
Install-Module Passwordstate-Management -RequiredVersion 4.4.11
Import-module Passwordstate-Management -RequiredVersion 4.4.11
Set-PasswordStateEnvironment -Baseuri 'https://pws.localhost.com' -WindowsAuthOnly -path c:\temp\4_11
$pwlist=Get-PasswordStateList -PasswordList 'pwlistname'
(Get-PasswordStatePassword -PasswordListID $pwlist.PasswordListID).count
~~~

Expected outcome: equal count value
Actual outcome: 4.4.9 returns value 50, 4.4.11 returns 1

**Comment by trir262** [comment]
This scenario is apparently not in my unit tests... I'll add it but we might need help from @eizedev to understand what has been changed

**Comment by eizedev** [comment]
Hmm...  This is weird.  I'll take a closer look at it later.

**Comment by dnewsholme** [comment]
It looks like Get-PSCustomObject only returns the last object in the array.

**Comment by eizedev** [comment]
@trir262 
Sorry, that wasn't supposed to happen. I think I have a solution for that, but I'd like to test it a little more. So I have removed this function from the 3 functions where it was already implemented.

@dnewsholme #105

**Comment by dnewsholme** [comment]
Issue is now fixed but we can leave this open if you plan to add the sorting back.

**Comment by trir262** [comment]
If it's the same for you, I'd prefer to keep it open as a placeholder for me for the tests... This is a scenario that should've been discovered by my pester tests

**Comment by trir262** [comment]
@dnewsholme I'll close this one as I have added this to my tests in #138
