### ISSUE TITLE
[Suggestion] New-PasswordStateResource - Cannot validate argument on parameter 'TimeoutSec'

### ISSUE THREAD

**Issue by eizedev** [dnewsholme/PasswordState-Management#106]
Edit: Sorry, i missed that this is only included in the `master` for now, not in the latest released version. Therefore this is only a suggestion from me ;-) 

@dnewsholme 

you have integrated the `TimeoutSeconds` property with a value of 60 to `Set-PasswordStateEnvironment` in the last commits. You referenced this variable and property in `New-PasswordStateResource` but for this to work you have to execute `Set-PasswordStateEnvironment` again so the newly created property `TimeoutSeconds` is there. (Get|Remove|Set-PasswordStateResource is still using the value of 60 directly)

I think it's better to check if the TimeoutSeconds property was found and if not, set a default value of 60 for the `-TimeoutSec` parameter (backwards compatibilty). For better usability i would suggest to add a parameter `TimeoutSeconds` to Set-PasswordStateEnvironment so that the user can control the timeout value. If the parameter was not specified, the default timeout of 60 will be used instead. (And of course, also to [Get|Set|Remove|New]-PasswordStateResource should then use the default value)

Alternatively, you could catch the error message if the `TimeoutSeconds` property was not found and throw an appropriate error message to the user that he/she should run Set-`PasswordStateEnvironment` again to set the timeout value.

If you like, I can implement one of the two variants and provide it as a pull request.

![image](https://user-images.githubusercontent.com/6794362/80913390-8660ba00-8d44-11ea-8ae1-9d33556a4b07.png)

(New-PasswordStateFolderPermission is not integrated at the moment, i will open a pull request if it's fully tested :))

**Comment by dnewsholme** [comment]
I think we can work around it by having Get-Passwordstateenvironment set timeout to 60 if it's null. 

Should be the quickest way with maintaining backwards compatibility i think?

**Comment by dnewsholme** [comment]
Something like this.

```powershell
 if ($null -eq $output.TimeoutSeconds){
            $output | Add-Member -MemberType NoteProperty -Name "TimeoutSeconds" -Value 60
        }
```
