### ISSUE TITLE
Move PasswordStateShowPasswordsPlainText parameter to environment

### ISSUE THREAD

**Issue by trir262** [dnewsholme/PasswordState-Management#108]
The module allows the (hidden) presence of a variable called "PasswordStateShowPasswordsPlainText". If this variable is declared AND it's value is $True, passwords are not encrypted but passed as clear text.

I would like this hidden gem to become part of the environment so people can decide for their on if they want to have it or not. By not specifying the option, it'll fall back to $False of course.
Additionally, prompting to confirm this selection sounds like a good plan as well to let people know what the impact will be.

Set-PasswordStateEnvironment would look like this:

~~~PowersShell
Set-PasswordStateEnvironment -Baseuri 'https://whatever' -SetPlainTextPasswords:$True
~~~

What do you think?

**Comment by trir262** [comment]
If the option is not mentioned, it'll fall back to $False of course

**Comment by dnewsholme** [comment]
Definitely makes sense to do this, we should use the environment file for storing all state information and it will make it more discoverable too.

**Comment by trir262** [comment]
oops, shouldn't have closed this yet as PR is still on the way
