### ISSUE TITLE
Get-PasswordStatePassword error if $Script:Preferences.Path is empty

### ISSUE THREAD

**Issue by eizedev** [dnewsholme/PasswordState-Management#110]
@trir262 

```powershell
$result = Get-PasswordStatePassword -Title $Title -UserName $Username
Exception:
Line |
  26 |              throw "No environment has been set. Run Set-PasswordState …
     |              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | No environment has been set. Run Set-PasswordStateEnvironment to create first.
```

In `passwordstate-management.psm1` the Path Key in `$Script:Preferences` object is by default empty 
```powershell
$Script:Preferences=[PSCustomObject]@{
	Path = ''
}
```

Only until you execute `Set-PasswordStateEnvironment -Path "..."` the `$Script:Preferences.Path` variable will be set and will then be not empty anymore.  

But in `Get-PasswordStatePassword` you are using this variable:

```powershell
$PWSProfile = Get-PasswordStateEnvironment -path $Script:Preferences.Path
```

So, in my understanding, in normal usage of the module, `$Script:Preferences.Path` should actually always be empty. 
By default the default **UserProfile** path will be used (`[Environment]::GetFolderPath('UserProfile')`).

Is there therefore something to be said against removing `$Script:Preferences.Path` from `Get-PasswordStatePassword` or am i missing something?

```Powershell
$PWSProfile = Get-PasswordStateEnvironment
```

Also the internal functions `Get-PasswordStateResource.ps1`, `New-PasswordStateResource.ps1`, `Set-PasswordStateResource.ps1` and `Remove-PasswordStateResource.ps1` only use `Get-PasswordStateEnvironment` without the Path parameter, so every function will only use the default UserProfile Path during execution.

**Comment by trir262** [comment]
René,
That is indeed something I have not taken into account. 
@dnewsholme I think my latest changes are best pulled from the gallery until this is resolved.

**Comment by dnewsholme** [comment]
I've unlisted 4.4.14 from the gallery until we can sort it.
