### ISSUE TITLE
Domain Parameter needs changing to ADDomainNetBIOS

### ISSUE THREAD

**Issue by dnewsholme** [dnewsholme/PasswordState-Management#117]
This parameter needs changing as the api does nothing with the current domain parameter.

Tests and class will need updating to reflect this.

**Comment by eizedev** [comment]
I think we should change the `Domain` variable to `ADDomainNetBIOS` and set an `Alias` (`[Alias('Domain')][string]$ADDomainNetBIOS`) for the old `Domain` variable to `ADDomainNetBIOS` to remain backward compatible.  
Also we need to change `Domain` to `ADDomainNetBIOS` in all pester tests and the Class definitions, as you already mentioned, too.

**Comment by trir262** [comment]
While looking in to this, I think I am going to need a bit more information on this: the attribute is present when retrieving a Password, however the value for `Domain` is blank in all my cases.
When trying to set a value for `Domain` it says all ok but nothing has changed.
Using PWS v9

**Comment by dnewsholme** [comment]
@trir262  i think for the domain to populate it has to be listed as one of the domain in the activedirectory section.

Once i did this i could then set a domain on my password.

```powershell
PS C:\Users\daryl> Get-PasswordStatePassword

PasswordID  : 1
Title       : test
Username    : test
Password    : refused-cNKM%T
Description :
Domain      :


PS C:\Users\daryl> Get-PasswordStatePassword -PasswordID 1 | Set-PasswordStatePassword -ADDomainNetBIOS "dnewsholme.co.uk"

PasswordID  : 1
Title       : test
Username    : test
Password    : refused-cNKM%T
Description :
Domain      :
```

Interesting the domain field didn't populate straight away in passwordstate as shown by the result above but when querying again after it did show the correct domain.

```powershell
PS C:\Users\daryl> Get-PasswordStatePassword

PasswordID  : 1
Title       : test
Username    : test
Password    : refused-cNKM%T
Description :
Domain      : dnewsholme.co.uk
```
