### ISSUE TITLE
Convert Pester Tests to v5

### ISSUE THREAD

**Issue by trir262** [dnewsholme/PasswordState-Management#137]
Hi @dnewsholme,
I noticed you had to reconfigure the appveyor so it uses Pester v4. I have been catching up on my pester testing skills and will make these tests v5 compliant.

**Comment by dnewsholme** [comment]
Hi @trir262.

Yeah it's no big deal if you want to take a look at converting to v5 then feel free. Just update the ./appveyor.yml at the same time in your pull request.

The line needed to change is, obviously specifying version 5.0

```yaml
install:  - cinst pester -y --version=4.10.1
```

Regards
