### ISSUE TITLE
Unable to change passwordstate when reason is required on passwordlist

### ISSUE THREAD

**Issue by trir262** [dnewsholme/PasswordState-Management#144]
The `Set-PasswordstatePassword` function looks up a password entry when the parameter PasswordID is used. it does this without providing a reason, causing it to fail.

**Comment by dnewsholme** [comment]
Yeah I see this now you mention it. I'll fix this tonight.

**Comment by trir262** [comment]
Gives you an opportunity to test the docker dev env :)

**Comment by dnewsholme** [comment]
Yeah the docker environment is really good. Thanks for adding, i really like it!
