### ISSUE TITLE
New-PasswordStateList can't be created in Advanced Folders

### ISSUE THREAD

**Issue by herobrauni** [dnewsholme/PasswordState-Management#155]
With #150 / #151 it is not possible to create Password Lists in Folders with the Advanced Folder Permission Model.

Password Lists should be created (and can be created via direct API call) without Permissions in Folders with the Advanced Permission Model, because they will inherit Permissions from the Parent Folder.

If I remove the Commit from #150 / #151 there is no Error and the List is created as expected (in a Advanced Permission Folder) , but then you get an error (again?) if you try to create a List without Permissions in a Standard Folder.

Solution might be to add a Switch / ParameterSet for "permissionless". 
Otherwise Folder should be checked if it is Advanced and Permission Check skipped.

**Comment by dnewsholme** [comment]
This has been fixed.
