### ISSUE TITLE
PowerShell gallery newer than GitHub releases?

### ISSUE THREAD

**Issue by miked1313** [dnewsholme/PasswordState-Management#161]
I noticed that the latest PowerShell gallery version is [4.4.47](https://www.powershellgallery.com/packages/passwordstate-management/4.4.47) and this repo only shows 4.4.4.  Is the latest source code that is published in the PowerShell Gallery viewable anywhere in GitHub?  Thank you.

**Comment by dnewsholme** [comment]
4.4.47 is the latest tip of the master branch. The release just wasn't tagged in github.

**Comment by miked1313** [comment]
Ahh, very well.  Thank you for updating it in GitHub.  Happy Holidays!
