### ISSUE TITLE
New-PasswordStateDocument returns "A parameter cannot be found that matches parameter name 'contentype'."

### ISSUE THREAD

**Issue by rousseyo** [dnewsholme/PasswordState-Management#168]
We've recently update the powershell module from 4.4.48 to 4.4.51, since then we noticed that the new-passwordstatedocument isn't saving the files anymore to passwordstate and we get following output
A parameter cannot be found that matches parameter name 'contentype'.

New-PasswordStatePassword -passwordlistID 1010 -Title $pwdstateTitle -username $username -password $pwd -GenericField1 $pfxPath -GenericField2 $keyValue -GenericField3 $certThumb -GenericField10 $pwdstateCustomer -notes $Note -description "Password needed to import pfx-file" -ExpiryDate $($endDate.ToString('yyyy-MM-dd'))

VERBOSE: Performing the operation "upload somecertificate.pfx on password with id 57476" on target "\\Security\Certificats\_Client_Certs\somecertificate\somecertificate.pfx".

We've already tried rolling back to 4.4.48 and 4.4.49, there the function is still working as intended and adding the documents to the password entry in passwordstate. Server version we are using is V9.9 (Build 9915)

**Comment by dnewsholme** [comment]
Thanks for raising this. Was a rather embarrassing typo on my behalf. This is now fixed in 4.4.52
