### ISSUE TITLE
passwordstate-management.psd1: Wrong required version

### ISSUE THREAD

**Issue by colombeen** [dnewsholme/PasswordState-Management#17]
Powershell version requirement should be 5. Powershell Classes are a part of WMF5.

**Comment by dnewsholme** [comment]
Yeah you're right it hasn't been updated since classes were implemented into the project. I'll update this in the next merge.

**Comment by colombeen** [comment]
Fixed: https://github.com/colombeen/PasswordState-Management/commit/8365e1fed1b588c402559139770d27991788b933
