### ISSUE TITLE
PasswordStateClass: change hidden properties to Default Display Property Set

### ISSUE THREAD

**Issue by colombeen** [dnewsholme/PasswordState-Management#39]
Just a suggestion, but couldn't it be done to change the hidden properties to normal properties and just add a default display property set to the object?

That way you'll be able to use `$PasswordStateObject | FL *` and see all properties, without having to force get-member to see them all

=> https://learn-powershell.net/2013/08/03/quick-hits-set-the-default-property-display-in-powershell-on-custom-objects/

**Comment by dnewsholme** [comment]
Didn't know you could do it like that, but makes sense to have the properties easily accessible/viewable.

Fixed in #40

**Comment by dnewsholme** [comment]
1.0.1 now in the powershell gallery

**Comment by colombeen** [comment]
Awesome! Thanks
