### ISSUE TITLE
Find-PasswordStatePassword: Remove multiple queries to PasswordState

### ISSUE THREAD

**Issue by colombeen** [dnewsholme/PasswordState-Management#48]
I'm trying to remove the foreach and end block (which aren't necessary in my opinion).

If I could replace line 174 with something like this (and remove the "&ExcludePassword=true" from the $uri) : 
```powershell
Get-PasswordStateResource -URI $uri @parms -Method GET | %{
  [PasswordResult]$obj  = $_
  If (!($global:PasswordStateShowPasswordsPlainText)) {
    $obj.Password = [EncryptedPassword]$obj.Password
  }
  $obj
}
```
then we could eliminate lines 179 -> 198
that would increase performance for the function

the only problem is that I can't seem to fix this "[PasswordResult]$obj  = $_"

I've also tried :
```powershell
[PasswordResult]Get-PasswordStateResource -URI $uri @parms -Method GET | %{
  If (!($global:PasswordStateShowPasswordsPlainText)) {
    $_.Password = [EncryptedPassword]$_.Password
  }
  $_
}
```
Any suggestions?

Error : 
```powershell
Cannot convert value "@{PasswordListID=123...xxxxx}" value of type "System.Management.Automation.PSCustomObject" to type "PasswordResult"."
At .\PasswordState-Management\Functions\Find-PasswordStatePassword.ps1:176 char:15
+               $obj  = [PasswordResult]$_
+               ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidCastConstructorException
```

**Comment by dnewsholme** [comment]
> I'm trying to remove the foreach and end block (which aren't necessary in my opinion).
> 
> If I could replace line 174 with something like this (and remove the "&ExcludePassword=true" from the $uri) :
> 
> ```powershell
> Get-PasswordStateResource -URI $uri @parms -Method GET | %{
>   [PasswordResult]$obj  = $_
>   If (!($global:PasswordStateShowPasswordsPlainText)) {
>     $obj.Password = [EncryptedPassword]$obj.Password
>   }
>   $obj
> }
> ```
> 
> then we could eliminate lines 179 -> 198
> that would increase performance for the function
> 
> the only problem is that I can't seem to fix this "[PasswordResult]$obj = $_"
> 
> I've also tried :
> 
> ```powershell
> [PasswordResult]Get-PasswordStateResource -URI $uri @parms -Method GET | %{
>   If (!($global:PasswordStateShowPasswordsPlainText)) {
>     $_.Password = [EncryptedPassword]$_.Password
>   }
>   $_
> }
> ```
> 
> Any suggestions?
> 
> Error :
> 
> ```powershell
> Cannot convert value "@{PasswordListID=123...xxxxx}" value of type "System.Management.Automation.PSCustomObject" to type "PasswordResult"."
> At .\PasswordState-Management\Functions\Find-PasswordStatePassword.ps1:176 char:15
> +               $obj  = [PasswordResult]$_
> +               ~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
>     + FullyQualifiedErrorId : InvalidCastConstructorException
> ```

The getting of the password result but excluding the password was originally used for before the Password was encrypted by the use of classes. It can now be removed.

However the response from the API from a password search and a get password by ID are slightly different so the cast to the class is failing. 

I'll pick this up, shouldn't take too long.

**Comment by colombeen** [comment]
Found the issue... Couldn't cast the PSCustomObject to the Class because it has 2 properties that aren't defined in the class : PasswordList & PasswordListID

This works : 
```powershell
Get-PasswordStateResource -URI $uri @params -Method GET | Select-Object * -ExcludeProperty PasswordListID,PasswordList | %{
  $obj  = [PasswordResult]$_
  If (!($global:PasswordStateShowPasswordsPlainText)) {
    $obj.Password = [EncryptedPassword]$obj.Password
  }
  $obj
}
```

Would you add the properties to the class? or would you exclude them like I did?

**Comment by dnewsholme** [comment]
Adding them to the class is cleaner.

I've got a working solution, but i'm going to leave the end block. (I know they aren't really needed but i like having the only returned object within the end block for ease of readability in the code, it makes a convention)

Just did a couple of speed tests before and after and for a result of 5 Password it's cut the time from 6 seconds to less than 2.

````
PS C:\Users\dnewsholme> Measure-command {Find-PasswordStatePassword dnewsholme}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 6
Milliseconds      : 15
Ticks             : 60159150
TotalDays         : 6.96286458333333E-05
TotalHours        : 0.0016710875
TotalMinutes      : 0.10026525
TotalSeconds      : 6.015915
TotalMilliseconds : 6015.915

````

and after

````
C:\git\PasswordState-Management [dev ≡ +0 ~2 -0 !]> Measure-command {Find-PasswordStatePassword dnewsholme}


Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 1
Milliseconds      : 691
Ticks             : 16912097
TotalDays         : 1.95741863425926E-05
TotalHours        : 0.000469780472222222
TotalMinutes      : 0.0281868283333333
TotalSeconds      : 1.6912097
TotalMilliseconds : 1691.2097
````

**Comment by dnewsholme** [comment]
#49 fixes the issue

**Comment by colombeen** [comment]
It's does increase performance alot, but if you leave the $output variable in the end block, and you have a query that would take 20 seconds and has alot of results, it would only show them when everything is processed...

If you remove the $output en return them directly you would at least see that the function is doing something and returning each record as it's being processed.

Just my personal preference to see results asap instead of having to wait for everything to have finished

**Comment by colombeen** [comment]
Also you left in an "&ExcludePassword=true"

**Comment by dnewsholme** [comment]
> It's does increase performance alot, but if you leave the $output variable in the end block, and you have a query that would take 20 seconds and has alot of results, it would only show them when everything is processed...
> 
> If you remove the $output en return them directly you would at least see that the function is doing something and returning each record as it's being processed.
> 
> Just my personal preference to see results asap instead of having to wait for everything to have finished

That's a good point. I guess having the stream of information is better for the pipeline too rather than forcing a wait. I'll update it and remove the exclude i missed too.

**Comment by dnewsholme** [comment]
Seem's i've somehow broken the Password history function as the Class inherits the PasswordResult Class. I'll look into that too.

**Comment by dnewsholme** [comment]
Was the PasswordList Property being inherited from PasswordResult Class but also declared on Password History. I also noticed the Password History Class wasn't displaying the right properties by default so i've updated that too.

**Comment by colombeen** [comment]
Did some heavy testing with the latest changes... These are my results : 

```powershell
PS C:\> # RESULT COUNT
PS C:\> (Find-PasswordStatePassword sys_).Count
1808
PS C:\> # OLDER VERSIONS OF THE MODULE (<= 2.1.0)
PS C:\> (Measure-Command { Find-PasswordStatePassword sys_ }).TotalSeconds
301,1719474
PS C:\> # CURRENT VERSION OF THE MODULE (= 2.2.0)
PS C:\> (Measure-Command { Find-PasswordStatePassword sys_ }).TotalSeconds
6,8457586
PS C:\> 
```

Ran this test multiple times, always around the same outcome

**Comment by dnewsholme** [comment]
I did a similar test. It's made a huge improvement in terms of speed.
