### ISSUE TITLE
Find-PasswordStatePassword: Can't search for username only

### ISSUE THREAD

**Issue by colombeen** [dnewsholme/PasswordState-Management#5]
When I try to search for the username, without using the title, I always get 0 results because you check if the title matches, even when there isn't one provided.

Line 94:
`$tempobj = $tempobj | Where-Object {$_.Title -eq $title -and $_.Username -eq $username}`

**Comment by dnewsholme** [comment]
@colombeen you are quite correct. My original use case was for searching by title and limiting the results by using the username parameter however this probably isn't the right way to do it, the filtering should be done outside the cmdlet and most people's use case would be to search by username only. I'll put up fix in an hour or two for this.

Thanks for letting me know.

**Comment by dnewsholme** [comment]
Resolved in merge #6. I've also published a new build to the powershell gallery with the fix.

https://www.powershellgallery.com/packages/passwordstate-management/0.0.88

**Comment by colombeen** [comment]
Thanks I'll try this out
