### ISSUE TITLE
PreventAuditing support for all functions

### ISSUE THREAD

**Issue by colombeen** [dnewsholme/PasswordState-Management#50]
Would be a nice feature to have (but low priority) so that you could prevent auditing when you don't need it.

` you can set the PreventAuditing parameter to true - if this parameter is omitted, the default option is false `

**Comment by dnewsholme** [comment]
Should be simple enough with a new switch parameter, i'll take a look over the next couple of days.

**Comment by dnewsholme** [comment]
resolved with #51. Build 2.3.0 should be up within a few minutes.
