### ISSUE TITLE
Pester Tests for *-PasswordStateHost

### ISSUE THREAD

**Issue by dnewsholme** [dnewsholme/PasswordState-Management#58]
#55  Added new functionality. New pester tests are required to ensure these keep working and aren't inadvertently broken with other changes.

**Comment by trir262** [comment]
Hello @dnewsholme, I would like to add unit tests for your module, however I would like to relayout your project by
* separate module functions from their tests files
* separate public and internal functions
* making use of PSFramework modules to simplify module development.

Is that OK for you?

**Comment by dnewsholme** [comment]
@trir262 Yes. Please feel free to do so. I know my module and function layouts aren't ideal and was on my list to sort so this would be a great help.

**Comment by trir262** [comment]
@dnewsholme Am I allowed to change the module name to something that does not contain a dash? Reason why I ask is because the dash makes it difficult to pour it into the framework. Any other character works fine (like "_" or "." or nothing and use initcaps).

**Comment by dnewsholme** [comment]
I'd rather not change the name as it would break existing integrations for others. What specific issue are you seeing?

**Comment by trir262** [comment]
You are right, don't want to ruin it right away :). I have updated the project in my repo and added a first batch of tests for Set-PasswordStateEnvironment. Tests should now be called from \tests\pester.ps1.
I have copied all your tests files but they seem to fail. I'll go over them one by one.

**Comment by dnewsholme** [comment]
Ah it may be my test server is not running. I'll check it out.

**Comment by trir262** [comment]
You don't have to run a test server: I explicitly do not want to connect to any webserver when invoking the unit tests. If later integration tests are built, maybe then

**Comment by trir262** [comment]
I have modified appveyor.yml so it starts 'my' pester. Unfortunately it does not allow uploading the invoked tests, but it will show you how many tests were executed and if any failed. You can see it in [https://ci.appveyor.com/project/TomRobijns/passwordstate-management](https://ci.appveyor.com/project/TomRobijns/passwordstate-management)

**Comment by dnewsholme** [comment]
Sorry i've not had much free time the last couple of days. That looks pretty good. 

I've looked at you branch and you have removed all the help text. What is the reasoning for this? Has it moved elsewhere?

**Comment by trir262** [comment]
Since the help is stored in the external 'doc' directory, it is a bit redundant to have it in the function files as well. I'd rather 'only' update the markdown files than updating both. 
When the documentation is updated, the external help (via PlatyPS) will be updated automatically.

**Comment by dnewsholme** [comment]
Those markdown were created from the help in the modules using platyps.

Does the get-help still work against the function doing it this way? Sorry
this is a new way of working for me and it's unfamiliar.

**Comment by trir262** [comment]
When you (initially) use PlatyPS to generate markdown files from your functions, you can safely remove the help from your functions themselves. From that point you can use PlatyPS update-markdown to update any changes (parameters,...).
Next step is to generate external help (xml) based on the markdown and your module will use that xml for it's help

**Comment by trir262** [comment]
Tests for Get-PasswordStateFolder have been added. Can you let me know what you think of them?

**Comment by dnewsholme** [comment]
That looks awesome. Some great pester tests there. Much more advanced.

**Comment by trir262** [comment]
I had to change the Set-PasswordState & Get-PasswordState, so they would retain that information while using the module (and not setting the environment variable. 
So #81 will be fixed with my changes as well.

**Comment by trir262** [comment]
Get-PasswordStateList unit tests are added as well.

**Comment by dnewsholme** [comment]
@trir262  here is the json you wanted.

`{
  "HostID": 1,
  "HostName": "dev01.contoso.com",
  "HostType": "Windows",
  "OperatingSystem": "Windows Server 2012",
  "DatabaseServerType": "",
  "SQLInstanceName": "",
  "DatabasePortNumber": "",
  "RemoteConnectionType": "RDP",
  "RemoteConnectionPortNumber": "3389",
  "RemoteConnectionParameters": "",
  "Tag": "",
  "Title": "dev01",
  "SiteID": "0",
  "SiteLocation": "Internal",
  "InternalIP": "",
  "ExternalIP": "",
  "MACAddress": "",
  "SessionRecording": false,
  "VirtualMachine": true,
  "VirtualMachineType": "Azure",
  "Notes": "",
  "DiscoveryJobID": null
}`

**Comment by trir262** [comment]
I added tests for Get-PasswordStatePasswordHistory, however the "PasswordID" needs to be present AND the number needs to correspond with an existing password. The module should report an error if these conditions are not met. I'll create a new issue for this.

**Comment by trir262** [comment]
I picked this up again and, based on your host json response, created tests for the "Get-PasswordstateHost" function
