### ISSUE TITLE
Find-PasswordStatePassword: Search for title isn't a real title search but a general search

### ISSUE THREAD

**Issue by colombeen** [dnewsholme/PasswordState-Management#7]
Search for title isn't a real title search but a general search

`$tempobj = Get-PasswordStateResource -uri "/api/searchpasswords/?search=$title&ExcludePassword=true"  -ErrorAction stop`

The documentation for the API shows that a title search uses **?title=$title** instead of **?search=$title**

the search is only used for general searches, not specific to titles only

- INFO FROM THE DOCUMENTATION
    # General Search by Password List
    $PasswordstateUrl = 'https://passwordstate/winapi/searchpasswords/<PasswordListID>?search=<value>&PreventAuditing=<value>'
                                
    # General Search across all Password Lists and all Fields 
    $PasswordstateUrl = 'https://passwordstate/winapi/searchpasswords/?search=<value>&PreventAuditing=<value>'
    
    # Specific Search, by 'Title', within a Password List
    $PasswordstateUrl = 'https://passwordstate/winapi/searchpasswords/<PasswordListID>?title=<value>&PreventAuditing=<value>'
    
    # Specific Search, by 'UserName', within a Password List
    $PasswordstateUrl = 'https://passwordstate/winapi/searchpasswords/<PasswordListID>?username=<value>&PreventAuditing=<value>'
    
    # Specific Search, by 'Title' and 'UserName', across all Password Lists
    $PasswordstateUrl = 'https://passwordstate/winapi/searchpasswords/?title=<value>&username=<value>&PreventAuditing=<value>'

'General Search' Instructions
When performing a General Search, it will query the Passwords table for fields which Contain the value you specify for the Search= parameter. The fields which will be searched are:
Title
ADDomainNetBIOS
HostName
UserName
AccountType
Description
GenericField1
GenericField2
GenericField3
GenericField4
GenericField5
GenericField6
GenericField7
GenericField8
GenericField9
GenericField10
Notes
URL
SiteID
SiteLocation

**Comment by dnewsholme** [comment]
I agree this should be changed the results don't match what is expected of the search.

**Comment by dnewsholme** [comment]
Search by title now correctly searches across title field only instead of all fields. A New parameter called searchterm has been created to replicate the old search and made the default first parameter to replicate the old use.

New module version up on the gallery.
https://www.powershellgallery.com/packages/passwordstate-management/0.0.89

Thanks again for submitting and putting together a thorough issue.
