### ISSUE TITLE
Passing a passwordstate entry to Update-PasswordstatePassword inadvertantly changes the password.

### ISSUE THREAD

**Issue by dnewsholme** [dnewsholme/PasswordState-Management#73]
Issue where when passing a password resource via the pipeline to Update-PasswordStatePassword the password could be inadvently changed to EncryptedPassword, when the intention was only to change another field.

eg:

```powershell
Get-PasswordStatePassword -PasswordID 1 | Update-PasswordStatePassword -url "https://google.com"
```

Result is the entry now has a Password of EncryptedPassword which isn't intended.

**Comment by dnewsholme** [comment]
@colombeen I see you have your own fork. You may want to pull in this change to your fork to prevent unintended updating of Passwords to incorrect values.

**Comment by colombeen** [comment]
Thx for the update @dnewsholme
