### ISSUE TITLE
Custom Class definitions are called everytime a call is done to PasswordState

### ISSUE THREAD

**Issue by trir262** [dnewsholme/PasswordState-Management#83]
When creating the tests, I discovered that whenever any function is used, it (almost) always starts with invoking the class definitions. Moving that bit to when the module is imported ensures they are defined.

**Comment by trir262** [comment]
In Get-PasswordStatePassword, you also always execute add-type System.Web. I don't really see why you do it, but I think it is also better moved to the import of the module.
These modifications speed up your module (a bit) and makes your code cleaner)

**Comment by dnewsholme** [comment]
With the class definition I couldn't find a way to reliably load it from the module definition file. System web could definitely be moved. Do you know of a way to load the class in the psm1 file?
