### ISSUE TITLE
Windows Auth Option Does Not Work

### ISSUE THREAD

**Issue by koshia** [dnewsholme/PasswordState-Management#95]
Environment Options:
Set-PasswordStateEnvironment -Baseuri "https://passwordstateurl.tld" -WindowsAuthOnly

Result:
PS C:\WINDOWS\system32> Get-PasswordStatePassword
The remote server returned an error: (401) Unauthorized.
At line:120 char:13
+             Throw $_.Exception
+             ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : The remote server returned an error: (401) Unauthorized.

Even though my account is authorized and I can log into the website just fine.

PasswordState is configured for Manual AD & 2FA - would 2FA break this?  I've tested disabling 2FA option under my account, but still received the (401) error.

When setting the environment to use passwordstate system-wide API key, it works just fine.

**Comment by dnewsholme** [comment]
Hi @koshia 

I've tried my end with module version 4.4.9 and it seems to work fine for me.

`PS C:\Users\dnewsholme> Set-PasswordStateEnvironment -Baseuri "https://pws.domain.co.uk" -WindowsAuthOnly`

`PS C:\Users\dnewsholme> Get-PasswordstatePassword test`

> PasswordID  : 6697
> Title       : testpassword123
> Username    : test123
> Password    : couch-7nQJSp3
> Description :
> Domain      :

I also enabled MFA with google authenticator and tried and it still worked.

If you can try running the command again and once you get the error run the following:

`$error[0] | select *`

It should show you the full error which might help narrow it down.

**Comment by koshia** [comment]
Thanks for responding so quickly. 


Here's the output for the error after i run Get-PasswordStatePassword -UserName root  - which i have a couple of accounts with root as the username and have access to them via the web-gui of passwordstate when I log in.

`PS H:\> $error[0] | select *


PSMessageDetails      :
Exception             : System.Net.WebException: The remote server returned an error: (401) Unauthorized.
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.GetResponse(WebRequest request)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : System.Net.HttpWebRequest
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand
ErrorDetails          : You do not have permission to view this directory or page.
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-PasswordStateResource<Process>, <No file>: line 94
                        at Get-PasswordStatePassword<Process>, <No file>: line 103
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}`

**Comment by dnewsholme** [comment]
@koshia  is it possible that the passwordstate server is on a different domain to the one your user account is logged in as?

**Comment by koshia** [comment]
> @koshia is it possible that the passwordstate server is on a different domain to the one your user account is logged in as?

The passwordstate server is on our domain, e.g. mydomain.org. Our accounts are on the same domain - typically logged in as mydomain\username  -- If i go to our passwordstate server's web GUI - the default login area shows "mydomain\" and we would type in our username after that.  That mydomain\  matches my current login of mydomain\username when I perform whoami in powershell/cmd.

**Comment by dnewsholme** [comment]
Can you try manually setting your windows credentials? E.G

```powershell
Set-PasswordstateEnvironment -baseuri "https://server.domain" -customcredential (Get-Credential)
```

It seems like it's potentially something to do with your browser or iis setup on the server.

https://www.clickstudios.com.au/community/index.php?/topic/1305-passwordstate-prompts-for-authentication/

Try checking out the steps here.

**Comment by koshia** [comment]
Figured it out!  Thanks for walking me through it so I could isolate the issue.

Resolution: We have our setup through webproxy. DNS was setup to hairpin, so the authentication was thrown to the proxy service instead of to the passwordstate server.  It's now been setup correctly and the integrated windows auth is working correctly.

Thanks!
